name: pad_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - seaborn
  - dash
  - jupyter
  - statsmodels
  - pip
  - pip:
      - plotly
